---
title: "Comparison between TG or RE with full PECA networks"
author: "Xiang Zhu"
date: "2018-07-19"
output: workflowr::wflow_html
---

```{r, echo=FALSE}
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(tidyr))
suppressPackageStartupMessages(library(ggpubr))
```

```{r, echo=FALSE}
res_path <- "~/Dropbox/rss/Data/peca_human/out_market/"

# load results of full networks
res_mat <- readRDS(paste0(res_path,"peca_human_ashlrt_20180724.rds"))
res_df <- as.data.frame(res_mat/log(10), row.names=NULL)
res_df$net_id <- (1:73)
res_df <- tidyr::gather_(res_df, key_col="trait", value_col="net_lr", gather_cols=colnames(res_mat))
net_res <- res_df

# load results of REs only
res_mat <- readRDS(paste0(res_path,"peca_re_human_ashlrt_20180724.rds"))
res_df <- as.data.frame(res_mat/log(10), row.names=NULL)
res_df$net_id <- (1:73)
res_df <- tidyr::gather_(res_df, key_col="trait", value_col="re_lr", gather_cols=colnames(res_mat))
re_res <- res_df

# load results of TGs only
res_mat <- readRDS(paste0(res_path,"peca_tg_human_ashlrt_20180724.rds"))
res_df <- as.data.frame(res_mat/log(10), row.names=NULL)
res_df$net_id <- (1:73)
res_df <- tidyr::gather_(res_df, key_col="trait", value_col="tg_lr", gather_cols=colnames(res_mat))
tg_res <- res_df

# combine results
full_res <- dplyr::inner_join(net_res, re_res, by=c("net_id","trait"))
full_res <- dplyr::inner_join(full_res, tg_res, by=c("net_id","trait"))

# remove results from urate2013
full_res <- full_res[full_res$trait!="urate2013", ]
```

Each dot represents a pair of a PECA network and a human trait.
The red lines are reference lines with slope one and intercept zero.

```{r, fig.width=12, fig.height=6, echo=FALSE}
tg_xlab <- "Log 10 likelihood ratio based on TGs of a PECA network only"
re_xlab <- "Log 10 likelihood ratio based on REs of a PECA network only"
net_ylab <- "Log 10 likelihood ratio based on a PECA network\n(including TGs, REs and TFs)" 

net_vs_tg <- ggscatter(full_res, x="tg_lr", y="net_lr", xlab=tg_xlab, ylab=net_ylab, cor.coef=TRUE, cor.coeff.args=list(method="pearson", label.y=1500, label.x=10, label.sep="\n")) + geom_abline(slope=1, intercept=0, color="red")
net_vs_re <- ggscatter(full_res, x="re_lr", y="net_lr", xlab=re_xlab, ylab=net_ylab, cor.coef=TRUE, cor.coeff.args=list(method="pearson", label.y=1500, label.x=1, label.sep="\n")) + geom_abline(slope=1, intercept=0, color="red")

ggarrange(net_vs_tg, net_vs_re, ncol=2)
```

A few observations:

- The full networks tend to capture more signal than TGs or REs alone.
- Signals of full networks correlate well with signals of TGs or REs alone.
- Signals of REs alone are much weaker than signals of TGs alone.
