---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: true
---

If you have any question about this project, please feel free to contact me:
[Xiang Zhu](https://github.com/xiangzhu), `xiangzhu@stanford.edu`.

***

## Software development

***

## Simulation study

- [Simulated summary-level data based on WTCCC & Liver-specific network](wtccc_sumstats_liver.html)
- [Simulated individual-level data based on WTCCC & Liver-specific network](wtccc_fulldata_liver.html)
    - [Assess the impact of TF](wtccc_fulldata_liver_tf.html)
    - [Assess the impact of TF-TG scores](wtccc_fulldata_liver_wt.html)
    - [Assess the impact of RE](wtccc_fulldata_liver_re.html)
- TBA

***

## Data analysis

### Likelihood ratio assessments

Below are some quick assessments of PECA networks I received from Duren,
using a simple likelihood ratio calculation introduced in
[Zhu and Stephens (2017)](https://doi.org/10.1101/160770).
The aim of these quick assessments is to confirms whether these networks
are informative in identifying disease-related tissues or cell types.

- [201 PECA networks and 31 human complex traits](ashlrt_201peca_31trait.html)
- [73 PECA networks and 33 human complex traits](ashlrt_73peca_33trait.html)
- [73 PECA networks (TG only) and 33 human complex traits](ashlrt_73peca_33trait_tg.html)
- [73 PECA networks (RE only) and 33 human complex traits](ashlrt_73peca_33trait_re.html)
- [Comparison between TG or RE with full PECA networks](ashlrt_73peca_33trait_compare.html)
- [66 MusDev lists and 33 human complex traits](ashlrt_66musdev_33traits.html)

### Application of new methods

Below are applications of the new methods to real datasets.

- [Late-onset Alzheimer's disease & Liver-specific network](load2013_liver.html)

### Miscellaneous investigations

- []
